# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-03 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('stock_count', models.IntegerField()),
            ],
            options={
                'db_table': 'stock',
            },
        ),
    ]
